RubyOnRails/members-only/config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  get 'signin' => 'sessions#new'
  delete 'signout' => 'sessions#destroy'
  resources :posts, only: [:new, :create, :index]
  root 'posts#index'

end

RubyOnRails/members-only/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

RubyOnRails/members-only/app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  before_create :create_remember_token

  has_secure_password
  validates :password, length: { minimum:4 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest token
    Digest::SHA1.hexdigest token.to_s
  end

  private

  def create_remember_token
    self.remember_token = User.digest(User.new_remember_token)
  end
end

RubyOnRails/members-only/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

RubyOnRails/members-only/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :signed_in_user, only: [:new, :create]

  def signed_in_user
    unless signed_in?
      redirect_to signin_url
    end
  end

  def index
    @posts = Post.all
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save
    redirect_to root_path
  end

  def new
    @post = Post.new
  end
  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

RubyOnRails/members-only/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "Thank you for signing in!"
      sign_in user
      redirect_to root_path
    else
      flash[:error] = 'Invalid information'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

RubyOnRails/members-only/app/helpers/application_helper.rb
module ApplicationHelper
end

RubyOnRails/members-only/app/helpers/posts_helper.rb
module PostsHelper
end

RubyOnRails/members-only/app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def signed_in?
    !current_user.nil?
  end
end

RubyOnRails/members-only/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MembersOnly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

RubyOnRails/members-only/app/views/posts/index.html.erb
<div class="float-right">
  <% if signed_in? %>
  <%= link_to "(#{current_user.name}) Sign out", signout_path, method: "delete" %>
  <% else %>
    <%= link_to 'Sign in', signin_path %>
  <% end %>
</div>

<h1>Members Only Posts</h1>

<% @posts.each do |post| %>
  <% if signed_in? %>
    <p class="float-right">
      Posted by:
      <%= post.user.name %>
    </p>
  <% end %>
  <h4 class="float-left"><%=post.title %></h4>
  <p class="clear"><%= post.body %></p>
<% end %>

<% if signed_in? %>
  <%= link_to "Create a Post", new_post_path %>
<% end %>

RubyOnRails/members-only/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for @post do |f| %>
  <p>
  <%= f.label :title %> <br/>
  <%= f.text_field :title %>
  </p>
  <p>
  <%= f.label :body %><br />
  <%= f.text_area :body %>
  </p>

  <p>
  <%= f.submit %>
  </p>
<% end %>